name: Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true

  - type: input
    id: unity-version
    attributes:
      label: Unity Version
      placeholder: "e.g., 2022.3.10f1"
    validations:
      required: true

  - type: input
    id: package-version
    attributes:
      label: WebView Toolkit Version
      placeholder: "e.g., 1.1.1"
    validations:
      required: true

  - type: dropdown
    id: graphics-api
    attributes:
      label: Graphics API
      options:
        - DirectX 11
        - DirectX 12
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Console Logs
      render: shell
